FROM node:16-alpine
WORKDIR /app

COPY src/frontend/package.json src/frontend/package-lock.json ./
RUN npm install --production

COPY src/frontend/ .

RUN npm run build

RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]